name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS
        uses: actions/setup-node@master

      - name: Install dependencies
        # Can't use CI because we need to install the legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
